language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "4.2"
  - "node"
script:
  - npm run lint
  - npm test
  - cd example; npm run lint
#after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
